language: java
jdk:
  - oraclejdk8

notifications:
  email: false

#run in container based hardware
sudo: false

before_install: chmod +x ./prepare-couchbase.sh ./stop-couchbase.sh ./gradlew

# magic
install: ./prepare-couchbase.sh

script: gradle build

after_script: ./stop-couchbase.sh
