language: java
jdk:
  - oraclejdk8

#run in container based hardware
sudo: false

before_install: chmod +x ./prepare-couchbase.sh ./stop-couchbase.sh ./gradlew

# magic
install: ./prepare-couchbase.sh

after_script: ./stop-couchbase.sh

# save directories of installed couchbase to reduce build time
cache:
  directories:
  - $HOME/opt
  - $HOME/etc
  - $HOME/usr