addons:
  artifacts:
    paths:
      - $HOME/logs.tar.gz
    s3_region: us-west-2

language: java
jdk:
  - oraclejdk8

notifications:
  email: false

#run in container based hardware
sudo: false

before_install: chmod +x ./prepare-couchbase.sh ./stop-couchbase.sh ./gradlew

# magic
install: ./prepare-couchbase.sh

after_script: ./stop-couchbase.sh
